# Generated by Django 3.2.6 on 2021-08-29 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, max_length=5)),
                ('activity', models.CharField(choices=[('Clown1 - Balloon Sorting', 'Clown1 - Balloon Sorting'), ('Clown2 - Clown Collar', 'Clown2 - Clown Collar'), ('Clown3 - Clown Face Paint', 'Clown3 - Clown Face Paint'), ('Clown4 - Hula Hoops', 'Clown4 - Hula Hoops'), ('Clown5 - Balloon Toss', 'Clown5 - Balloon Toss')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Incipient', 'Incipient'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
