# Generated by Django 3.2.6 on 2021-08-29 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clownApp', '0002_clown_clown'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clown',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='clownApp.clown'),
        ),
    ]
