# Generated by Django 3.2.6 on 2021-08-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clownApp', '0003_appointment_clown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='clown',
            name='activity',
        ),
        migrations.AddField(
            model_name='appointment',
            name='activity',
            field=models.CharField(choices=[('Clown1 - Balloon Sorting', 'Clown1 - Balloon Sorting'), ('Clown2 - Clown Collar', 'Clown2 - Clown Collar'), ('Clown3 - Clown Face Paint', 'Clown3 - Clown Face Paint'), ('Clown4 - Hula Hoops', 'Clown4 - Hula Hoops'), ('Clown5 - Balloon Toss', 'Clown5 - Balloon Toss')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clown',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Incipient', 'Incipient'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
