# Generated by Django 3.2.6 on 2021-08-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clownApp', '0005_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
